// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // 🚩 [INJECTED] เพิ่ม DIRECT_URL เพื่อให้ Supabase ยอมให้มึง Push ข้อมูลขึ้นไปได้
    directUrl: env("DIRECT_URL"), 
  },
});